# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e25b7f73dcc134f4c6d7f38a72a6f27e53d8f8ac8462ae22f6143d9d2aa6c65d9fc0382b49e696ef982ec830bc4913dc6b4ebd42ce03883b5ce819d50c9a39f5

test:
  secret_key_base: f4d07b491879f9c35273710fda8f2d7f70aef41b4d60269ee4efb85a969f7d8d45c921fb57bd994b4081c7c7ba0c202616fc5d13dd6125b608bc649b7a7acba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
